### ISSUE TITLE
Gunrack key not working?

### ISSUE THREAD

**Issue by AndreasFromDanmark** [swkeep/keep-gunrack#2]
![image](https://user-images.githubusercontent.com/35656492/190250002-30bc52d4-eb4a-4d44-828d-9556fd978ad1.png)
![image](https://user-images.githubusercontent.com/35656492/190250077-d09d6812-4ae2-4e98-8f1e-3688071ac092.png)
![image](https://user-images.githubusercontent.com/35656492/190250104-f5dbc403-6bd8-493e-a0a1-82d63b116101.png)

**Comment by swkeep** [comment]
Did you tried to cut keys?

**Comment by swkeep** [comment]
Have you tried cutting the keys?

**Comment by AndreasFromDanmark** [comment]
@swkeep I found the problem, if you are not writes the number plate with all CAPS. it will not work

![image](https://user-images.githubusercontent.com/35656492/190552331-78fe672b-477a-4a47-94fa-63c0cbd7d441.png)
![image](https://user-images.githubusercontent.com/35656492/190552344-eaffb4eb-a701-4336-9d45-4b77babfd426.png)
